### ISSUE TITLE
Microsoft Power Platform Dataverse

### ISSUE THREAD

**Issue by asubhash2023** [jklotzsche-msft/TeamsPhoneNumberManagement#1]
Dear @jklotzsche-msft 
Thanks for sharing the solution.

I am a Power App developer and developing a similar application.

Power Apps Canvas - UI
Power Platform Dataverse - DB.

Please help with code/Power Shell Modules to use Dataverse instead of SQL.

**Comment by jklotzsche-msft** [comment]
Hi @asubhash2023, please contact me directly, so we can maybe merge our projects for one, complete solution. Thank you :-)
