### ISSUE TITLE
The number +12XXXXXXXXX is not part of any existing range. Continuing with the next number.

### ISSUE THREAD

**Issue by asubhash2023** [jklotzsche-msft/TeamsPhoneNumberManagement#4]
I see warning, 
![Screenshot2024-09-17170411](https://github.com/user-attachments/assets/027a35de-8955-4b84-b56b-f67a24c8b2e8)

**Comment by asubhash2023** [comment]
<img width="465" alt="image" src="https://github.com/user-attachments/assets/c3346e23-5eb7-4424-b5bf-3c6eb569353c">


But Now Rows created.

**Comment by jklotzsche-msft** [comment]
Hi @asubhash2023 , have you added the related extension range to your database?

**Comment by asubhash2023** [comment]
Hi 

I have not added. Let me trying adding the range to our database.

**Comment by jklotzsche-msft** [comment]
Resolved by adding the needed country, department and extension range to the database.
